[dev_tooling]
YOUR_IP_ADDRESS_HERE ansible_python_interpreter=

[dev_tooling:vars]
; for ec2 this would be 'admin'
ansible_user=
; for ec2 this would a path to your pem file
ansible_ssh_private_key_file=
